//! 构建脚本：
//! 1. 把素材目录的 webm 打包成 assets.pak 并生成索引源码（assets_gen.rs）；
//! 2. 定位 libvpx 静态库（vpx.lib / vpxmd.lib）并输出链接指令。
//!
//! 素材目录解析优先级：DESKPET_VIDEOS_DIR 环境变量 > 仓库根 assets/videos（crate 位于仓库根）。
//! libvpx 解析优先级：VPX_LIB_DIR 环境变量 > VCPKG_ROOT/installed/x64-windows/lib > vendor_libvpx/x64/Release（上游约定路径）。

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());

    // ---------- 素材目录 ----------
    let videos = resolve_videos_dir(&manifest);
    println!("cargo:rerun-if-changed={}", videos.display());
    println!("cargo:rerun-if-env-changed=DESKPET_VIDEOS_DIR");

    // 扫描所有 webm 素材
    let mut entries: Vec<PathBuf> = fs::read_dir(&videos)
        .expect("assets/videos 目录缺失")
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().map_or(false, |e| e == "webm"))
        .collect();
    entries.sort();

    if entries.is_empty() {
        panic!("{} 下没有 webm 素材", videos.display());
    }

    // 拼接成单个 pak + 生成索引
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let mut pak: Vec<u8> = Vec::new();
    let mut table: Vec<(String, usize, usize)> = Vec::new();
    for p in &entries {
        let name = p.file_stem().unwrap().to_str().unwrap().to_string();
        let data = fs::read(p).unwrap();
        let start = pak.len();
        pak.extend_from_slice(&data);
        table.push((name, start, data.len()));
    }
    fs::write(out_dir.join("assets.pak"), &pak).unwrap();

    // 生成索引 rust 源码
    let mut code = String::new();
    code.push_str("// auto-generated by build.rs\n");
    code.push_str("pub static ASSET_PAK: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/assets.pak\"));\n");
    code.push_str("pub static ANIMS: &[(&str, usize, usize)] = &[\n");
    for (name, start, len) in &table {
        let escaped = name.replace('\\', "\\\\").replace('"', "\\\"");
        code.push_str(&format!("    (\"{}\", {}, {}),\n", escaped, start, len));
    }
    code.push_str("];\n");
    fs::write(out_dir.join("assets_gen.rs"), code).unwrap();

    // ---------- libvpx 链接 ----------
    let target = env::var("TARGET").unwrap_or_default();
    if target.contains("apple-darwin") {
        link_libvpx_macos();
    } else {
        link_libvpx_windows(&manifest);
    }
}

fn resolve_videos_dir(manifest: &Path) -> PathBuf {
    if let Ok(dir) = env::var("DESKPET_VIDEOS_DIR") {
        if !dir.trim().is_empty() {
            let p = PathBuf::from(dir);
            if p.is_dir() {
                return p;
            }
        }
    }
    let local = manifest.join("assets").join("videos");
    if local.is_dir() {
        return local;
    }
    panic!(
        "找不到 webm 素材目录。请先运行 tools/fetch-webm-assets.ps1（或 .sh）获取素材，\
         或用环境变量 DESKPET_VIDEOS_DIR 指向素材目录。"
    );
}

fn link_libvpx_windows(manifest: &Path) {
    println!("cargo:rerun-if-env-changed=VPX_LIB_DIR");
    println!("cargo:rerun-if-env-changed=VCPKG_ROOT");

    let mut candidates: Vec<PathBuf> = Vec::new();
    if let Ok(dir) = env::var("VPX_LIB_DIR") {
        if !dir.trim().is_empty() {
            candidates.push(PathBuf::from(dir));
        }
    }
    if let Ok(root) = env::var("VCPKG_ROOT") {
        candidates.push(PathBuf::from(root).join("installed").join("x64-windows").join("lib"));
    }
    // 上游约定路径（按 README 构建 libvpx 后产物在此）
    candidates.push(manifest.join("vendor_libvpx").join("x64").join("Release"));

    for dir in &candidates {
        if !dir.is_dir() {
            continue;
        }
        if dir.join("vpx.lib").is_file() {
            println!("cargo:rustc-link-search=native={}", dir.display());
            println!("cargo:rustc-link-lib=static=vpx");
            return;
        }
        if dir.join("vpxmd.lib").is_file() {
            println!("cargo:rustc-link-search=native={}", dir.display());
            println!("cargo:rustc-link-lib=static=vpxmd");
            return;
        }
    }
    // 仅做 cargo check 时（DESKPET_ALLOW_NO_LIBVPX=1）缺库不报错：check 不链接，
    // 真实构建/链接会以 "cannot find -lvpx" 明确报错。
    println!("cargo:warning=libvpx 未找到。若为 cargo check 可忽略；真实构建请先安装 libvpx 并设置 VPX_LIB_DIR。");
    if env::var("DESKPET_ALLOW_NO_LIBVPX").is_ok() {
        return;
    }
    panic!(
        "找不到 libvpx 静态库（vpx.lib / vpxmd.lib）。\
         请先安装：vcpkg install libvpx:x64-windows，然后设置 VPX_LIB_DIR 指向其 lib 目录；\
         或按上游方式在 vendor_libvpx/x64/Release 放置 vpxmd.lib。\
         （仅做 cargo check 时可用 DESKPET_ALLOW_NO_LIBVPX=1 跳过）"
    );
}

/// macOS：homebrew / vcpkg 或 VPX_LIB_DIR 中的 libvpx（静态 .a 优先，其次动态 .dylib）。
fn link_libvpx_macos() {
    println!("cargo:rerun-if-env-changed=VPX_LIB_DIR");
    println!("cargo:rerun-if-env-changed=VCPKG_ROOT");

    let mut candidates: Vec<PathBuf> = Vec::new();
    if let Ok(dir) = env::var("VPX_LIB_DIR") {
        if !dir.trim().is_empty() {
            candidates.push(PathBuf::from(dir));
        }
    }
    if let Ok(root) = env::var("VCPKG_ROOT") {
        let root = PathBuf::from(root);
        candidates.push(root.join("installed").join("arm64-osx").join("lib"));
        candidates.push(root.join("installed").join("x64-osx").join("lib"));
    }
    // homebrew（Apple Silicon / Intel）
    candidates.push(PathBuf::from("/opt/homebrew/lib"));
    candidates.push(PathBuf::from("/usr/local/lib"));

    for dir in &candidates {
        if !dir.is_dir() {
            continue;
        }
        if dir.join("libvpx.a").is_file() {
            println!("cargo:rustc-link-search=native={}", dir.display());
            println!("cargo:rustc-link-lib=static=vpx");
            return;
        }
        if dir.join("libvpx.dylib").is_file() {
            println!("cargo:rustc-link-search=native={}", dir.display());
            println!("cargo:rustc-link-lib=vpx");
            return;
        }
    }
    println!("cargo:warning=libvpx 未找到（macOS）。若为 cargo check 可忽略；真实构建请先安装 libvpx 并设置 VPX_LIB_DIR。");
    if env::var("DESKPET_ALLOW_NO_LIBVPX").is_ok() {
        return;
    }
    panic!(
        "找不到 libvpx 库（libvpx.a / libvpx.dylib）。\
         请先安装：brew install libvpx（或 vcpkg install libvpx），\
         或用 VPX_LIB_DIR 指向其 lib 目录。\
         （仅做 cargo check 时可用 DESKPET_ALLOW_NO_LIBVPX=1 跳过）"
    );
}
